### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by mdraw** [conda-forge/fish-feedstock#1]
Currently MacOS builds are disabled due to this error: https://travis-ci.org/conda-forge/staged-recipes/builds/179060101
I have no idea how to fix this, so any help for making the builds run on Travis is much appreciated.

**Comment by zanchey** [comment]
https://travis-ci.org/conda-forge/staged-recipes/builds/179060101#L541 is concerning. If you can get a `config.log` out of Travis (I usually use `./configure ... || cat config.log`), that might help.

**Comment by jakirkham** [comment]
Seems to be that there is no `pcre2`. TBH not sure how it is passing on Linux without this. Perhaps it is using a system copy. 😕

```bash
configure: error: At least one of the 8, 16 or 32 bit libraries must be enabled
configure: error: ./configure failed for pcre2-10.21
```

Anyways I would trying adding `pcre2` to staged-recipes and once it gets converted to a feedstock give it another go. You may be able to borrow code from our [`pcre`]( https://github.com/conda-forge/pcre-feedstock ) recipe to do so.

xref: https://travis-ci.org/conda-forge/staged-recipes/builds/179060101#L669-L670

**Comment by mdraw** [comment]
> Perhaps it is using a system copy.

It does. According to https://github.com/fish-shell/fish-shell#building:
> fish requires PCRE2 due to the regular expression support contained in the string builtin. A copy is included with the source code, and will be used automatically if it does not already exist on your system.

If we can make pcre2 available as a separate package, this should be fixed.

**Comment by zanchey** [comment]
I still don't think it will work. The `configure` line I pointed to above is detecting the byte width of `wchar_t` as 0, which means it's going to go looking for a pcre2 library that does not (cannot) exist.

**Comment by mdraw** [comment]
Resolved by #9.
I don't know anyone who uses both MacOS and conda, so I'd be grateful if anyone could verify that it actually works. (Travis has only verified that `fish --help` and `fish_indent --help` exit with `0`).

**Comment by mdraw** [comment]
Build broke again with 3.1.0. I tried to enable builds again in #20, but it fails and I don't understand the error.

**Comment by jakirkham** [comment]
Probably time for a new issue
